# Template only. Apply your own postgres data in a secure way.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: dGVzdA==
  POSTGRES_USER: dGVzdA==
  POSTGRES_PASSWORD: dGVzdA==
