# TODO: This config map is bad as it exposes the secrets.
# How do I set this up as actual secrets?
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test