apiVersion: v1
kind: Service
metadata:
  name: grpc-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc-server
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    component: grpc
  sessionAffinity: None
  type: LoadBalancer
